### PR TITLE
fix misspell scan failure

### PR DESCRIPTION
**Pull request by sunyuan3**
Signed-off-by: Yuan Sun <yile.sy@alibaba-inc.com>

### CODE REVIEW

**Comment by denverdino** [comment]
Can we also scan non-ascii char?

**Comment by sunyuan3** [comment]
@denverdino I have a try. The misspell tool can't scan the error of non-ascii char. I need to research other tools.

log: "wrang" is not found.
```
root@85190ec0146c:/tmp# cat README.md
This is a wrang word.
root@85190ec0146c:/tmp# if LC_ALL=C grep -q '[![:cntrl:][:print:]]' README.md; then   echo "Contain Non-ASCII"; fi
Contain Non-ASCII
root@85190ec0146c:/tmp# misspell -error README.md
root@85190ec0146c:/tmp# echo $?
0
```

**Comment by sunyuan3** [comment]
I used the mdspell tool, which can scan non-ascii char for markdown files.  However, some custom words are scanned as error, such as terway & aliyun. I have to create a custom dictionary to ignore them.

mdspell:
屏幕快照 2019-07-02 上午11 53 47

**Comment by denverdino** [comment]
Warning should be fine. Error is too strict. Thanks

**Comment by sunyuan3** [comment]
@denverdino Could you please review this pull request?

**Pull request merged**
