### PR TITLE
fix: missing volume config in terway.yml

### PR DESCRIPTION
**Pull request by BetaCat0**
Fix missing volume config in terway.yml which will cause terway to panic.

### CODE REVIEW

**Comment by BSWANG** [comment]
LGTM 
Thanks! @BetaCat0

**Comment by BetaCat0** [comment]
Hi guys, I also suggest that you could post the limitation of ENI allocation which mentioned in [here](https://help.aliyun.com/document_detail/25378.html?spm=5176.10695662.1996646101.searchclickresult.79fb7ba4QIXzyE), you know, it will raise an error like "xx Insufficient aliyun/eni" when you trying to claim ENI. Furthermore, how about add a `trouble shooting` part in readme 😀?

**Comment by BSWANG** [comment]
@BetaCat0 🙂 Yes, we should add `trouble shooting` section or document link in readme. I create an issue to trace this request #10.

**Comment by BetaCat0** [comment]
This is gonna be nice. Thanks a lot.

**Pull request merged**
